# Generated by Django 6.0.5 on 2026-08-15 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PGC', 'Perecederos, granos y cereales'), ('FYV', 'Frutas y verduras'), ('LYD', 'Lácteos y derivados'), ('HYP', 'Huevos y proteínas'), ('DYP', 'Derivados y panadería'), ('DYC', 'Despensas y conservas'), ('BYA', 'Bebidas y aromáticas'), ('SMS', 'Semillas')], max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('peso', models.DecimalField(decimal_places=3, help_text='Peso en kilogramos', max_digits=8)),
                ('imagen', models.ImageField(upload_to='productos/img/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
