# Generated by Django 6.0.5 on 2026-06-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('detalle_producto', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=3, max_digits=8)),
                ('imagen', models.ImageField(upload_to='productos/img/')),
                ('categoria', models.CharField(choices=[('GYC', 'Granos y cereales'), ('FYV', 'Frutas y verduras'), ('LYD', 'Lácteos y derivados'), ('HYP', 'Huevos y proteínas'), ('DYP', 'Derivados y panadería'), ('DYC', 'Despensas y conservas'), ('BYA', 'Bebidas y aromáticas'), ('SMS', 'Semillas')], max_length=3)),
            ],
        ),
    ]
