# Generated by Django 6.0.5 on 2026-08-15 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PDT', 'Pendiente'), ('ENP', 'En preparación'), ('CPO', 'Completado'), ('CLO', 'Cancelado')], max_length=3)),
                ('direccion_entrega', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ciudad', models.CharField(choices=[('BGT', 'Bogotá'), ('CAL', 'Cali'), ('MDN', 'Medellín'), ('BQA', 'Barranquilla'), ('MNS', 'Manizales')], max_length=3)),
                ('metodo_pago', models.CharField(choices=[('EFO', 'Efectivo'), ('TRF', 'Transferencia'), ('PSE', 'PSE (Pagos en línea)'), ('BDS', 'Billeteras dígitales')], max_length=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.pedido')),
            ],
        ),
    ]
